FROM server.aiknown.cn:31003/z_ai_frame/alpine-python3

COPY "./requirements.txt" "./requirements.txt"
COPY "./requirements_all.txt" "./requirements_all.txt"

RUN pip3 install  -i https://mirrors.aliyun.com/pypi/simple/  -r ./requirements_all.txt --use-deprecated=legacy-resolver