FROM  server.aiknown.cn:31003/z_ai_frame/alpine-python3:latest

COPY "./" "./"

RUN pip3 install  -i https://mirrors.cloud.tencent.com/pypi/simple/ --extra-index-url  https://pypi.org/simple/  -r ./requirements_all.txt &&  apk del .build_dependencies
RUN ln -sf /usr/bin/python3 /usr/bin/python

CMD gunicorn -w 4 -t 120 -b 0.0.0.0:5000 run:app

