FROM wuhanchu/python:3_alpine
USER root


COPY "./requirements.txt" "./requirements.txt"
COPY "./requirements_all.txt" "./requirements_all.txt"

RUN pip3 install  -i https://mirrors.cloud.tencent.com/pypi/simple/ --extra-index-url  https://pypi.org/simple/  -r ./requirements_all.txt --use-deprecated=legacy-resolver